# Generated by Django 2.2.1 on 2019-05-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
